name: Linter

on: push

jobs:
  linter:
    name: linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # https://github.com/marketplace/actions/python-code-quality-and-lint
    - uses: ricardochaves/python-lint@v1.3.0
      with:
        use-pylint: false
        use-pycodestyle: false
        use-flake8: true
        use-black: true
        use-mypy: true
        use-isort: true
        # extra-flake8-options: ""
        extra-black-options: "-l 79"
        # extra-isort-options: ""
